### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by yakschuss** [tpope/rbenv-ctags#11]
Sorry if this isn't the right place for this - I want rbenv-ctags for the tag jumping capability, but I don't want vim to index the tags for autocomplete. How do I turn this off? I'd like to limit the `completeopt` options to my project specific tags. Thanks!

**Comment by tpope** [comment]
You can `:set complete-=t` but unfortunately I don't think you can get any more granular than that.

**Comment by yakschuss** [comment]
Thanks!
