### ISSUE TITLE
Query about installation

### ISSUE THREAD

**Issue by gayanW** [tpope/rbenv-ctags#12]
I'm not sure if I'm missing something, but I can't seem to figure out from where the `rbenv ctags` exectuable comes.

I tried running  `rbenv-ctags/bin/rbenv-ctags` executable while in `~/.rbenv/plugins/rbenv-ctags` directory. But it results in:

    bin/rbenv-ctags: line 54: rbenv-versions: command not found

**Comment by tpope** [comment]
Right executable, but `rbenv` has to invoke it, not you.
