### ISSUE TITLE
Use supported implementation of ctags

### ISSUE THREAD

**Issue by jfoy** [tpope/rbenv-ctags#17]
Consider using [Universal Ctags](https://ctags.io/) ([repo](https://github.com/universal-ctags/ctags)), which has the stated goal of being a supported successor to Exuberant Ctags. For the purposes of rbenv-ctags it seems to be a drop-in replacement.

**Comment by tpope** [comment]
It uses whatever ctags is in the path. That should work fine for Universal Ctags. I don't think there's anything here to do?
