### ISSUE TITLE
No Ruby include directory for ctags found in ~/.rbenv/versions/<number>

### ISSUE THREAD

**Issue by ivan-kolmychek** [tpope/rbenv-ctags#8]
After installing `rbenv-ctags`, whenever I install new version of ruby with `rbenv install` or run `rbenv ctags <version>` I get such output: 

    Running ctags on /home/ivanko/.rbenv/versions/2.1.7/lib/ruby/2.1.0
    No Ruby include directory for ctags found in /home/ivanko/.rbenv/versions/2.1.7

The `vim-rbenv` plugin does find the stdlib tags anyway.

Is this ok?

**Comment by ivan-kolmychek** [comment]
Not sure is it related or not, but with `rbenv-ctags` installed and this error, the `rbenv-default-gems` plugin does not seems to work - gems from `$(rbenv root)/default-gems` are not being installed. 

If I remove the `rbenv-ctags`, the "default" gems are installed ok.

**Comment by tpope** [comment]
Can't reproduce.
https://github.com/tpope/rbenv-ctags/blob/905fd3971160ad26773af1bcfa31562f265a97fd/bin/rbenv-ctags#L45
is
the conditional that's failing if you want to investigate further.

Failure to generate ctags does indeed abort the rest of the installation,
which I think is the correct semantic?

**Comment by ivan-kolmychek** [comment]
Yes, it looks like it fails because of my setup - I've avoided modifying `$PATH` and mixing rbenv into the shell, but just added aliases the needed commands with `rbenv exec blahblah`. This way whatever may need system ruby does not get messed up.

So, If I create an empty folder and set ruby version there

    [ivanko] ~ 
    $ mkdir rbenv-2.1.7-test
    [ivanko] ~ 
    $ cd rbenv-2.1.7-test/
    [ivanko] ~/rbenv-2.1.7-test 
    $ rbenv local 2.1.7
    [ivanko] ~/rbenv-2.1.7-test 
    $ rbenv local
    2.1.7

and run the command from script

    [ivanko] ~/rbenv-2.1.7-test 
    $ RBENV_VERSION=2.1.7 ruby -rrbconfig -e 'print RbConfig::CONFIG["rubyhdrdir"] || RbConfig::CONFIG["topdir"]'
    /usr/include/ruby-2.3.0

Of course, `/usr/inlcude/ruby-2.3.0` is not writable by my user.

if I prefix it with `rbenv exec`, path is correct.

    [ivanko] ~/rbenv-2.1.7-test 
    $ RBENV_VERSION=2.1.7 rbenv exec ruby -rrbconfig -e 'print RbConfig::CONFIG["rubyhdrdir"] || RbConfig::CONFIG["topdir"]'
    /home/ivanko/.rbenv/versions/2.1.7/include/ruby-2.1.0

Can script be modified to not assume that user let the default `ruby` command be managed by rbenv? For instance, by running `rbenv exec ruby` instead of just `ruby`?

**Comment by ivan-kolmychek** [comment]
Also yes, that's a correct semantic, I guess, but I was not sure, so I've asked. 

I think, the message may be improved by adding something like "Installation aborted" in the end.

**Comment by tpope** [comment]
That sounds like it would work yes.

**Comment by ivan-kolmychek** [comment]
It looks like the PR #7 is actualy about this - can you, please check it and accept it if it's ok? That would be really awesome.
